import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";  //don't remove this import because then we cannot use tailwindcss, layout file is essentially the setting for the UI that is applied throughout the entire project, so it's important that this import remains as it is within the layout section
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PriceScape",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Navbar />
        {children}
        </body>
    </html>
  );
}
